version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268:14268"
      - "9411:9411"
      - "3200:3200"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana-hackathon
    ports:
      - "3001:3000"  # Expose grafan Dashboard
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

volumes:
  prometheus-data:
  grafana-storage: